config/routes.rb
Rails.application.routes.draw do
  resources :urls, only: [:index, :new, :create, :show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/url.rb
class Url < ApplicationRecord

  validates :long_url, presence: true, length: { minimum: 30}

  # before_create :generate_short_url, :sanitize
  
  def generate_short_url
    rand(36**8).to_s(36)
  end
  def sanitize
    long_url.strip!
    sanitize_url = self.long_url.downcase.gsub(/(https?:\/\/)|(www\.)/,"")
    "http://#{sanitize_url}"
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController

  def index
    @urls = Url.all
  end

  def new
    @url = Url.new
  end

  def create
    @url = Url.new(url_params)
    @url.short_url =@url.generate_short_url
    @url.long_url = @url.sanitize
    if @url.save
      redirect_to urls_path
    else
      flash[:error] = @url.errors.full_messages
      redirect_to new_url_path
    end
  end

  def show
    print params
    @url = Url.find_by(id: params[:id])
    redirect_to @url.long_url,allow_other_host: true
  end

  private
  
  def url_params
    params.require(:url).permit(:long_url,:short_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlTask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/index.html.erb
<table>
<% @urls.each do |user| %>
	<tr>
		<th>Short URL</th>
		<th>Long URL</th>
	</tr>
  <tr>
    <td><%= link_to "http://url/r/"+user.short_url, url_path(user) %></td> 
    <td><%= user.long_url %></td>
  </tr>
<% end %>
</table>
<br>
<br>
<br>
<%= link_to 'Create another link', new_url_path %>

app/views/urls/new.html.erb
<%= flash[:error] %>
<%= form_with model: @url do |form| %>
  <p>Please input url you want to shorten: <%= form.text_field :long_url %></p>
  <%= form.submit %>
<% end %>

app/views/urls/show.html.erb
<h1>Urls#show</h1>
<p>Find me in app/views/urls/show.html.erb</p>